services:
   postgres:
      image: postgres:latest
      container_name: tasks
      environment:
         POSTGRES_DB: tasks
         POSTGRES_USER: root
         POSTGRES_PASSWORD: changemeinprod
      ports:
         - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -d tasks"]
         interval: 10s
         timeout: 5s
         retries: 5
      restart: always

volumes:
   postgres_data:
